package com.movtery.buildkeys.core

import com.movtery.buildkeys.core.obfuscation.StringObfuscator

class BuildKeysGenerator(
    private val packageName: String,
    private val items: List<ItemConfig>,
    private val obfuscator: StringObfuscator
) {
    fun generate(): String {
        val sb = StringBuilder()

        sb.appendLine("/**")
        sb.appendLine(" * Automatically generated file. DO NOT MODIFY")
        sb.appendLine(" *")
        sb.appendLine(" * This class is automatically generated by the BuildKeys Gradle plugin.")
        sb.appendLine(" * Any manual changes will be overwritten on the next build.")
        sb.appendLine(" */")
        sb.appendLine("@file:Suppress(\"unused\")")
        sb.appendLine()

        sb.appendLine("package $packageName")
        sb.appendLine()

        sb.appendLine("object BuildKeys {")

        for ((i, item) in items.withIndex()) {
            if (i > 0) sb.appendLine()
            generateItem(item, sb, obfuscator)
        }

        sb.appendLine("}")
        return sb.toString()
    }

    private fun generateItem(
        item: ItemConfig,
        sb: StringBuilder,
        obfuscator: StringObfuscator
    ) {
        when (item.type) {
            "String" if item.hidden -> {
                val obfuscated = obfuscator.obfuscate(item.value)
                val decodeExpr = obfuscated.runtimeExpression.replace("{LIT}", obfuscated.literal)
                sb.appendLine("    val ${item.key}: String by lazy {")
                sb.appendLine("        $decodeExpr")
                sb.appendLine("    }")
            }
            "String" -> {
                sb.appendLine("    const val ${item.key}: String = \"${escapeString(item.value)}\"")
            }
            "Int" -> {
                sb.appendLine("    const val ${item.key}: Int = ${item.value}")
            }
            "Float" -> {
                sb.appendLine("    const val ${item.key}: Float = ${kotlinFloatLiteral(item.value)}")
            }
            "Double" -> {
                sb.appendLine("    const val ${item.key}: Double = ${kotlinDoubleLiteral(item.value)}")
            }
            "Long" -> {
                sb.appendLine("    const val ${item.key}: Long = ${item.value}L")
            }
            "Boolean" -> {
                sb.appendLine("    const val ${item.key}: Boolean = ${item.value}")
            }
        }
    }

    private fun kotlinFloatLiteral(value: String): String = when (value) {
        "NaN" -> "Float.NaN"
        "Infinity" -> "Float.POSITIVE_INFINITY"
        "-Infinity" -> "Float.NEGATIVE_INFINITY"
        else -> "${value}f"
    }

    private fun kotlinDoubleLiteral(value: String): String = when (value) {
        "NaN" -> "Double.NaN"
        "Infinity" -> "Double.POSITIVE_INFINITY"
        "-Infinity" -> "Double.NEGATIVE_INFINITY"
        else -> value
    }

    private fun escapeString(value: String): String {
        return value
            .replace("\\", "\\\\")
            .replace("\"", "\\\"")
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
            .replace("$", "\\$")
    }
}
